Strapi Setup and Page Integration (/press , /press/___ , /team , /team/___)
CivicActions/civicactions.com pull request #919
Opened 2021-02-15 22:38 UTC by Yodart

Sites is now importing data from Strapi for those pages and rendering it without styling changes.

2021-02-17 11:30 UTC, iris-i commented
@Yodart
Some graphQL queries in `src/templates/caseStudyTemplate2.js` are causing this to fail.
Let's remove all changes to Case studies since this PR is just for Team and Press. We also don't want to display the stringified json objects on those pages until the variables are successfully displaying the data from the CMS.

2021-02-17 11:33 UTC, iris-i requested changes
@Yodart
Some graphQL queries in `src/templates/caseStudyTemplate2.js` are causing this to fail.
Let's remove all changes to Case studies since this PR is just for Team and Press. We also don't want to display the stringified json objects on those pages until the variables are successfully displaying the data from the CMS.

2021-03-05 16:43 UTC, iris-i commented
Build url: http://home-919.ci.civicactions.net/

2021-03-09 13:53 UTC, iris-i requested changes
@Yodart  this looks good, a few minor changes are needed.

2021-03-09 13:53 UTC, iris-i commented on src/pages/case-study.js
> +//   }
Let's delete this instead of commenting it out. It can be restored from git history if needed in the future.

2021-03-09 13:53 UTC, iris-i commented on src/templates/caseStudyTemplate.js
> +//   }
Same feedback as above: Can this be deleted instead of uncommented.

2021-03-09 13:53 UTC, iris-i commented on src/templates/caseStudyTemplate2.js
> +// `
See above.

2021-03-09 13:53 UTC, iris-i commented on src/templates/press.js
> +
Nice job on the pagination!

2021-03-09 13:53 UTC, iris-i commented on src/templates/teamMemberTemplate.js
> +  )
@Yodart are we no longer showing medium posts for team members? Fwiw I no longer see them in the current site so maybe the answer is yes?

2021-03-23 16:38 UTC, Yodart commented
Closing this as the current homesite won't be integrated with Strapi anymore, only the new homesite

2021-03-23 16:38 UTC, closed without merging